"""Resolve the prepared release through Maven and verify the downloaded bytes."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
from urllib.parse import unquote
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = "spark-doris-connector-spark-3.5"
VERSION = "26.1.0-cve.1"
parser = argparse.ArgumentParser()
parser.add_argument("--maven", default=shutil.which("mvn"))
parser.add_argument("--java-home", default=os.environ.get("JAVA_HOME"))
parser.add_argument("--maven-repository", type=Path)
args = parser.parse_args()
if not args.maven or not args.java_home:
    parser.error("Set JAVA_HOME and provide Maven on PATH or --maven")
out = ROOT / "release-output"
repo = out / "maven"
relative = Path("io/github/cklinisme") / ARTIFACT / VERSION / f"{ARTIFACT}-{VERSION}.jar"
expected = hashlib.sha256((repo / relative).read_bytes()).hexdigest()
audit = json.loads((out / "audit.json").read_text(encoding="utf-8"))
if expected != audit["sha256"] or audit["errors"]:
    raise SystemExit("Release JAR does not match the audited artifact")
consumer = ROOT / ".build/release-consumer"
consumer.mkdir(parents=True, exist_ok=True)
cache = args.maven_repository.resolve() if args.maven_repository else ROOT / ".build/repository"
(consumer / "pom.xml").write_text(f'''<project xmlns="http://maven.apache.org/POM/4.0.0">
 <modelVersion>4.0.0</modelVersion><groupId>local.validation</groupId>
 <artifactId>release-consumer</artifactId><version>1</version>
 <repositories><repository><id>prepared-security-fork</id><url>{escape(unquote(repo.as_uri()))}</url></repository></repositories>
 <dependencies><dependency><groupId>io.github.cklinisme</groupId>
 <artifactId>{ARTIFACT}</artifactId><version>{VERSION}</version></dependency></dependencies>
</project>''', encoding="utf-8")
env = dict(os.environ, JAVA_HOME=args.java_home)
env["PATH"] = str(Path(args.java_home) / "bin") + os.pathsep + env.get("PATH", "")
tree_path = consumer / "dependency-tree.txt"
command = [args.maven, "-B", "-ntp", "-U", "-f", str(consumer / "pom.xml"),
           "-Dmaven.repo.local=" + str(cache), "org.apache.maven.plugins:maven-dependency-plugin:3.6.1:resolve",
           "org.apache.maven.plugins:maven-dependency-plugin:3.6.1:tree",
           "-DoutputFile=" + str(tree_path)]
with (out / "maven-consumer.log").open("w", encoding="utf-8") as log:
    subprocess.run(command, cwd=ROOT, env=env, stdout=log, stderr=subprocess.STDOUT, check=True)
downloaded = cache / relative
actual = hashlib.sha256(downloaded.read_bytes()).hexdigest()
if actual != expected:
    raise SystemExit("Maven resolved different JAR bytes")
tree = tree_path.read_text(encoding="utf-8")
lines = [line for line in tree.splitlines() if line.strip()]
if len(lines) != 2 or f"io.github.cklinisme:{ARTIFACT}:jar:{VERSION}:compile" not in tree:
    raise SystemExit("Unexpected transitive dependencies: " + tree)
result = {"status": "passed", "repository": "local file repository generated by prepare_release.py",
          "publicDownloadVerified": False, "coordinate": f"io.github.cklinisme:{ARTIFACT}:{VERSION}",
          "sha256": actual, "dependencyTree": tree}
(out / "maven-consumer.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
verification = out / "VERIFICATION.md"
if verification.exists():
    content = verification.read_text(encoding="utf-8").split("\n## Maven 發布包解析驗證\n")[0]
    verification.write_text(content + "\n## Maven 發布包解析驗證\n\n"
        "已由獨立 Maven 專案，透過本機 file repository 解析發布包，下載的 JAR SHA-256 與已掃描成品相同。\n"
        "依賴樹只有新座標，不會再拉回舊版 Connector 或未發布的 fork 模組。\n"
        "這是本機發布包驗證；公開 Maven Central 的下載驗證仍待正式發布後執行。\n", encoding="utf-8")
print(tree.strip())
print("PASS: Maven resolved the standalone release POM and matching audited JAR")
# Copyright 2026 cklinisme
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
